### ISSUE TITLE
fresh installation on a clean system does not go smoothly.

### ISSUE THREAD

**Issue by m0jek** [Dejvino/birdie#2]
make install-deb needs to be ran under sudo.
Also the missing sub directors are not made and need to be manually done fist before running the install. 

This is an example the error, happens for /usr/share/birdie as well 

```
install -D -o root -g root -m 4755 set-user-alarm /usr/lib/birdie/libexec/set-user-alarm
install: cannot create directory '/usr/lib/birdie/libexec': No such file or directory
make[1]: *** [Makefile:19: install] Error 1
```

**Comment by Dejvino** [comment]
Thanks for reporting this! Should be fixed in 14831c3f31827d0377f2e024bacbdca66173058d.
