### ISSUE TITLE
No audio on alarm

### ISSUE THREAD

**Issue by joshbowyer** [Dejvino/birdie#3]
Built for Mobian with Phosh on Pinephone (will post my exact steps below as an added bonus, I think Birdie will be great and have already added it to the Mobian wiki in the apps list)

When the alarm goes off, the lock screen notification appears, but there is no audio. I havent been able to get the audio to play.

Installation steps:

```
git clone https://github.com/Dejvino/birdie
cd birdie
sudo apt install gcc make checkinstall python3-psutil gnome-session-canberra python3-pip
sudo pip install mpris-server
sudo mkdir -p /usr/lib/birdie/libexec
sudo mkdir /usr/share/birdie
sudo make install-deb
```

**Comment by Dejvino** [comment]
@joshbowyer Thanks for the support! I finally got to test the app on Mobian and the steps helped a lot.

As for the alarm sound, turns out there is no `python` on Mobian, just `python3`. This should be fixed now (14831c3f31827d0377f2e024bacbdca66173058d).
