### ISSUE TITLE
needed to unmask system-wake-up.timer

### ISSUE THREAD

**Issue by abugher** [Dejvino/birdie#5]
Platform is a new PinePhone, running up to date Mobian and Phosh.

I followed the install instructions for Mobian, with one exception:  I did `pip install mpris-server` as my limited user, rather than root.

When toggling the "scheduled" slider, birdie showed me red error text, indicating the alarm was not set and I should see console output.  I ran birdie from an SSH session, toggled the slider again (from off to on), and observed this:

```
Failed to enable unit: Unit file /etc/systemd/system/system-wake-up.timer is masked.
Command '['/usr/lib/birdie/libexec/set-user-alarm', '2021-07-02 12:00:00']' returned non-zero exit status 255.
```

In another shell, I did this:

```
mobian@mobian:~$ sudo systemctl unmask system-wake-up.timer
[sudo] password for mobian: 
Removed /etc/systemd/system/system-wake-up.timer.
mobian@mobian:~$ 
```

After that, and after toggling the slider one more time, the alarm seemed to get set.  It went off at the appropriate time.

**Comment by Dejvino** [comment]
I couldn't find why the timer would get masked. Apart from the deb package getting uninstalled, when reportedly Debian automatically masks the provided services (and re-enables them on install). But I couldn't reproduce on the latest Mobian Bookworm.

**Comment by abugher** [comment]
I'm sorry that I can't offer more information at this point.  My pinephone is currently out of commission with hardware issues.  When/if those are resolved, I will attempt to repro on latest Mobian.  (I'm losing confidence that will happen.)  It sounds like currently no one can repro with latest platform and application software.

Closing.  Not reproducible, possibly fixed in recent versions of application and/or platform.
