### ISSUE TITLE
Would love to help expand this but can't find contact info

### ISSUE THREAD

**Issue by chookity-pokk** [Dejvino/birdie#6]
I want to make a few changes to the app to add an option for optimal wake times for users. I am a bit confused on how to alarm is actually set (I don't know any C and don't have experience with systemd timers) but can carry my own weight with the Python programming. So if maybe I could get an email address or you just email me at hank.greenburg(at)protonmail.com I would appreciate it.

**Comment by Dejvino** [comment]
Sure! I sent you a message.
