### ISSUE TITLE
No sound on Arch ARM

### ISSUE THREAD

**Issue by hellia-be** [Dejvino/birdie#7]
I installed with:
```
git clone https://github.com/Dejvino/birdie.git
cd birdie  
pip3 install -r requirements.txt  
sudo make install
```

But when testing the alarm, I have no sound at all. Other sounds are outputted correctly from the system.

**Comment by Dejvino** [comment]
Installing on a fresh Arch, I found it couldn't play the ogg alarm sound. It was missing some GStreamer dependencies: `extra/gst-plugins-base`, `extra/gst-plugins-good`

Try running the `play-alarm-sound` app to see if there are any errors in the console.

**Comment by hellia-be** [comment]
Working now, extra/gst-plugins-base was indeed missing.
Might be good to add it in the README.md
